spring:
  redis:
    host: 192.168.196.128
    port: 6379
    database: 0
    timeout: 10000ms # 客户端超时时间 2.0版本要加单位
    jedis: # springboot 2.0 有两种客户端jedis和lettuce，这里使用jedis
      pool:
        max-idle: 100 # 最大空闲数
        min-idle: 0 # 最小空闲数
        max-active: 1000 #控制一个pool可分配多少个jedis实例
        max-wait: 2000ms #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。